micronaut:
  application:
    name: qr-code-storage-service
  server:
    port: 8083
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
